# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    
    #git_pull

    cocoapods
    
  end

  desc "Build"
  private_lane :build do

    increment_build_number # version bump

    gym(
      scheme: "li5"
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      clean: true,
      scheme: "li5"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    build # Build your app - more options available

    produce(
      app_version: '0.1'
    )

    pilot(
      skip_submission: true
    )

    commit_version_bump(
      message: 'Build Version Bump by fastlane',
      force: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    increment_version_number(
      bump_type: 'patch'
    )

    gym(scheme: "li5") # Build your app - more options available

    produce(
      app_version: '0.1'
    )

    deliver(
      skip_deploy: true,
      force: true,
      app_version: "0.1"
    )
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(
      message: "Successfully deployed new App Update.",
      channel: "li5-apps"
     )
  end

  error do |lane, exception|
     slack(
       message: exception.message,
       channel: "li5-apps",
       success: false
     )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
